import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Learning NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <Link href={'/users'}>Users</Link>
        </h1>
        <h1>
          <Link href={'/posts'}>Posts</Link>
        </h1>
      </main>
    </>
  )
}

export default Home
